# From https://github.com/alebelcor/alacritty-snazzy/blob/master/snazzy.yml
draw_bold_text_with_bright_colors: true
colors:
  primary:
    background: '#282a36'
    foreground: '#eff0eb'

  cursor:
    cursor: '#97979b'

  selection:
    text:       '#282a36'
    background: '#feffff'

  normal:
    black:   '#282a36'
    red:     '#ff5c57'
    green:   '#5af78e'
    yellow:  '#f3f99d'
    blue:    '#57c7ff'
    magenta: '#ff6ac1'
    cyan:    '#9aedfe'
    white:   '#f1f1f0'

  bright:
    black:   '#686868'
    red:     '#ff5c57'
    green:   '#5af78e'
    yellow:  '#f3f99d'
    blue:    '#57c7ff'
    magenta: '#ff6ac1'
    cyan:    '#9aedfe'
    white:   '#eff0eb'

font:
  size: 14.0
  normal:
    family: JetBrainsMonoNL Nerd Font Mono
    #    family: MesloLGS Nerd Font Mono
window:
  dimensions:
    columns: 100
    lines: 44
