# Config relating to the Lazygit UI
gui:
  # Config relating to the spinner.
  spinner:
    # The frames of the spinner animation.
    frames:
      - "⠋"
      - "⠙"
      - "⠹"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
      - "⠇"
      - "⠏"
    # The "speed" of the spinner in milliseconds.
    rate: 50
